#############################################################################
# Makefile for building: discazos-creator
# Generated by qmake (2.01a) (Qt 4.7.4) on: mié may 30 18:22:29 2012
# Project:  discazos-creator.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile discazos-creator.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu /usr/lib/libtag.so -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/gui/discazoscreator.cpp \
		src/gui/intropage.cpp \
		src/gui/albuminfopage.cpp \
		src/gui/discform.cpp \
		src/models/mp3tracksmodel.cpp \
		src/models/mp3track.cpp \
		src/models/albuminfo.cpp \
		src/main.cpp \
		src/models/disc.cpp \
		src/gui/savediscazopage.cpp \
		src/libmp3basics/mp3_file.cpp \
		src/libmp3basics/mp3_frame.cpp \
		src/libmp3basics/mp3_file_reader.cpp moc_discazoscreator.cpp \
		moc_intropage.cpp \
		moc_albuminfopage.cpp \
		moc_discform.cpp \
		moc_mp3tracksmodel.cpp \
		moc_mp3track.cpp \
		moc_albuminfo.cpp \
		moc_disc.cpp \
		moc_savediscazopage.cpp
OBJECTS       = discazoscreator.o \
		intropage.o \
		albuminfopage.o \
		discform.o \
		mp3tracksmodel.o \
		mp3track.o \
		albuminfo.o \
		main.o \
		disc.o \
		savediscazopage.o \
		mp3_file.o \
		mp3_frame.o \
		mp3_file_reader.o \
		moc_discazoscreator.o \
		moc_intropage.o \
		moc_albuminfopage.o \
		moc_discform.o \
		moc_mp3tracksmodel.o \
		moc_mp3track.o \
		moc_albuminfo.o \
		moc_disc.o \
		moc_savediscazopage.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		discazos-creator.pro
QMAKE_TARGET  = discazos-creator
DESTDIR       = 
TARGET        = discazos-creator

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_intropage.h ui_albuminfopage.h ui_discform.h ui_savediscazopage.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: discazos-creator.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile discazos-creator.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile discazos-creator.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/discazos-creator1.0.0 || $(MKDIR) .tmp/discazos-creator1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/discazos-creator1.0.0/ && $(COPY_FILE) --parents src/gui/discazoscreator.h src/gui/intropage.h src/gui/albuminfopage.h src/gui/discform.h src/models/mp3tracksmodel.h src/models/mp3track.h src/models/albuminfo.h src/models/disc.h src/gui/savediscazopage.h src/libmp3basics/mp3_frame.h src/libmp3basics/mp3_file_reader.h src/libmp3basics/mp3_file.h .tmp/discazos-creator1.0.0/ && $(COPY_FILE) --parents src/gui/discazoscreator.cpp src/gui/intropage.cpp src/gui/albuminfopage.cpp src/gui/discform.cpp src/models/mp3tracksmodel.cpp src/models/mp3track.cpp src/models/albuminfo.cpp src/main.cpp src/models/disc.cpp src/gui/savediscazopage.cpp src/libmp3basics/mp3_file.cpp src/libmp3basics/mp3_frame.cpp src/libmp3basics/mp3_file_reader.cpp .tmp/discazos-creator1.0.0/ && $(COPY_FILE) --parents src/gui/intropage.ui src/gui/albuminfopage.ui src/gui/discform.ui src/gui/savediscazopage.ui .tmp/discazos-creator1.0.0/ && (cd `dirname .tmp/discazos-creator1.0.0` && $(TAR) discazos-creator1.0.0.tar discazos-creator1.0.0 && $(COMPRESS) discazos-creator1.0.0.tar) && $(MOVE) `dirname .tmp/discazos-creator1.0.0`/discazos-creator1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/discazos-creator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_discazoscreator.cpp moc_intropage.cpp moc_albuminfopage.cpp moc_discform.cpp moc_mp3tracksmodel.cpp moc_mp3track.cpp moc_albuminfo.cpp moc_disc.cpp moc_savediscazopage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_discazoscreator.cpp moc_intropage.cpp moc_albuminfopage.cpp moc_discform.cpp moc_mp3tracksmodel.cpp moc_mp3track.cpp moc_albuminfo.cpp moc_disc.cpp moc_savediscazopage.cpp
moc_discazoscreator.cpp: src/gui/discazoscreator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gui/discazoscreator.h -o moc_discazoscreator.cpp

moc_intropage.cpp: src/gui/intropage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gui/intropage.h -o moc_intropage.cpp

moc_albuminfopage.cpp: src/models/albuminfo.h \
		src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/gui/albuminfopage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gui/albuminfopage.h -o moc_albuminfopage.cpp

moc_discform.cpp: src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/gui/discform.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gui/discform.h -o moc_discform.cpp

moc_mp3tracksmodel.cpp: src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/models/mp3tracksmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/models/mp3tracksmodel.h -o moc_mp3tracksmodel.cpp

moc_mp3track.cpp: src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/models/mp3track.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/models/mp3track.h -o moc_mp3track.cpp

moc_albuminfo.cpp: src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/models/albuminfo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/models/albuminfo.h -o moc_albuminfo.cpp

moc_disc.cpp: src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/models/disc.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/models/disc.h -o moc_disc.cpp

moc_savediscazopage.cpp: src/gui/savediscazopage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/gui/savediscazopage.h -o moc_savediscazopage.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_intropage.h ui_albuminfopage.h ui_discform.h ui_savediscazopage.h
compiler_uic_clean:
	-$(DEL_FILE) ui_intropage.h ui_albuminfopage.h ui_discform.h ui_savediscazopage.h
ui_intropage.h: src/gui/intropage.ui
	/usr/bin/uic-qt4 src/gui/intropage.ui -o ui_intropage.h

ui_albuminfopage.h: src/gui/albuminfopage.ui
	/usr/bin/uic-qt4 src/gui/albuminfopage.ui -o ui_albuminfopage.h

ui_discform.h: src/gui/discform.ui
	/usr/bin/uic-qt4 src/gui/discform.ui -o ui_discform.h

ui_savediscazopage.h: src/gui/savediscazopage.ui
	/usr/bin/uic-qt4 src/gui/savediscazopage.ui -o ui_savediscazopage.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

discazoscreator.o: src/gui/discazoscreator.cpp src/gui/discazoscreator.h \
		src/gui/intropage.h \
		src/gui/albuminfopage.h \
		src/models/albuminfo.h \
		src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/gui/savediscazopage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o discazoscreator.o src/gui/discazoscreator.cpp

intropage.o: src/gui/intropage.cpp src/gui/intropage.h \
		ui_intropage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intropage.o src/gui/intropage.cpp

albuminfopage.o: src/gui/albuminfopage.cpp src/gui/albuminfopage.h \
		src/models/albuminfo.h \
		src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		ui_albuminfopage.h \
		src/gui/discform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o albuminfopage.o src/gui/albuminfopage.cpp

discform.o: src/gui/discform.cpp src/gui/discform.h \
		src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		ui_discform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o discform.o src/gui/discform.cpp

mp3tracksmodel.o: src/models/mp3tracksmodel.cpp src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp3tracksmodel.o src/models/mp3tracksmodel.cpp

mp3track.o: src/models/mp3track.cpp src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp3track.o src/models/mp3track.cpp

albuminfo.o: src/models/albuminfo.cpp src/libmp3basics/mp3_file_reader.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h \
		src/models/albuminfo.h \
		src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o albuminfo.o src/models/albuminfo.cpp

main.o: src/main.cpp src/gui/discazoscreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

disc.o: src/models/disc.cpp src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o disc.o src/models/disc.cpp

savediscazopage.o: src/gui/savediscazopage.cpp src/gui/savediscazopage.h \
		ui_savediscazopage.h \
		src/gui/albuminfopage.h \
		src/models/albuminfo.h \
		src/models/disc.h \
		src/models/mp3tracksmodel.h \
		src/models/mp3track.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savediscazopage.o src/gui/savediscazopage.cpp

mp3_file.o: src/libmp3basics/mp3_file.cpp src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp3_file.o src/libmp3basics/mp3_file.cpp

mp3_frame.o: src/libmp3basics/mp3_frame.cpp src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp3_frame.o src/libmp3basics/mp3_frame.cpp

mp3_file_reader.o: src/libmp3basics/mp3_file_reader.cpp src/libmp3basics/mp3_file_reader.h \
		src/libmp3basics/mp3_file.h \
		src/libmp3basics/mp3_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp3_file_reader.o src/libmp3basics/mp3_file_reader.cpp

moc_discazoscreator.o: moc_discazoscreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_discazoscreator.o moc_discazoscreator.cpp

moc_intropage.o: moc_intropage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_intropage.o moc_intropage.cpp

moc_albuminfopage.o: moc_albuminfopage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_albuminfopage.o moc_albuminfopage.cpp

moc_discform.o: moc_discform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_discform.o moc_discform.cpp

moc_mp3tracksmodel.o: moc_mp3tracksmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mp3tracksmodel.o moc_mp3tracksmodel.cpp

moc_mp3track.o: moc_mp3track.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mp3track.o moc_mp3track.cpp

moc_albuminfo.o: moc_albuminfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_albuminfo.o moc_albuminfo.cpp

moc_disc.o: moc_disc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_disc.o moc_disc.cpp

moc_savediscazopage.o: moc_savediscazopage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savediscazopage.o moc_savediscazopage.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

